version: "3.7"
services:
  db:
    image: mysql:8.0.23
    platform: linux/amd64
    restart: always
    container_name: paperware
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=paperware
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_USER=paperware
      - MYSQL_PASSWORD=0000
    command:
      - --log-bin=mysql-bin
      - --server-id=1
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
  shadow_db:
    image: mysql:8.0.23
    platform: linux/amd64
    restart: always
    container_name: shadow-paperware-template
    ports:
      - 3307:3307
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=paperware
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_USER=paperware
      - MYSQL_PASSWORD=0000
    command:
      - --log-bin=mysql-bin
      - --server-id=1
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/shadow/mysql:/var/lib/mysql
  redis:
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis:/var/lib/redis
    env_file:
      - .env
