-- AlterTable
ALTER TABLE `Order` MODIFY `status` ENUM('ORDER_PREPARING', 'ORDER_CANCELLED', 'ORDER_REQUESTED', 'ORDER_ACCEPTED', 'ORDER_REJECTED', 'STOKC_OFFER_PREPARING', 'STOCK_OFFER_REQUESTED', 'STOCK_OFFER_ACCEPTED') NOT NULL DEFAULT 'ORDER_PREPARING';
