-- AlterTable
ALTER TABLE `Plan` ADD COLUMN `orderReturnId` INTEGER NULL,
    MODIFY `type` ENUM('INHOUSE_CREATE', 'INHOUSE_MODIFY', 'INHOUSE_RELOCATION', 'INHOUSE_PROCESS', 'INHOUSE_STOCK_QUANTITY_CHANGE', 'TRADE_NORMAL_SELLER', 'TRADE_NORMAL_BUYER', 'TRADE_WITHDRAW_SELLER', 'TRADE_WITHDRAW_BUYER', 'TRADE_OUTSOURCE_PROCESS_SELLER', 'TRADE_OUTSOURCE_PROCESS_BUYER', 'RETURN_SELLER', 'RETURN_BUYER') NOT NULL;

-- AddForeignKey
ALTER TABLE `Plan` ADD CONSTRAINT `Plan_orderReturnId_fkey` FOREIGN KEY (`orderReturnId`) REFERENCES `OrderReturn`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
