-- AlterTable
ALTER TABLE `OrderHistory` MODIFY `type` ENUM('CREATE', 'ACCEPT', 'PLAN_START', 'PLAN_CANCEL', 'ORDER_CANCEL', 'OFFER_REQUEST', 'OFFER_REQUEST_CANCEL', 'OFFER_REQUEST_REJECT', 'ORDER_REQUEST', 'ORDER_REQUEST_CANCEL', 'ORDER_REQUEST_REJECT') NOT NULL;
