-- AlterTable
ALTER TABLE `Order` MODIFY `status` ENUM('ORDER_PREPARING', 'ORDER_REQUESTED', 'ORDER_REJECTED', 'OFFER_PREPARING', 'OFFER_REQUESTED', 'OFFER_REJECTED', 'ACCEPTED', 'ORDER_CANCELLED', 'OFFER_CANCELLED') NOT NULL DEFAULT 'ORDER_PREPARING';
