export const PAPER_DOMAIN = [
  '산업용지',
  '인쇄용지',
  '복사용지',
  '식품용지',
  '신문용지',
  '특수지',
];
export const MANUFACTURER = [
  '한국제지',
  '한솔제지',
  '세하',
  '한창제지',
  '무림페이퍼',
  '무림SP',
  '무림P&P',
  '깨끗한나라',
  '삼화제지',
  '대화제지',
  '홍원제지',
  '고려제지',
  '페이퍼코리아',
  '전주페이퍼',
  'Double A',
];
export const PAPER_GROUP = [
  '갱판지',
  '경량코트지',
  '마닐라 양면합지',
  '마닐라 크라프트',
  '마닐라 합지',
  '미량코트지(MFC)',
  '백상지',
  '보루지',
  '보루지 합지',
  '아트지',
  '양KB',
  '크라프트(양면)',
  '흑지',
  'AB',
  'B',
  'CB',
  'CCP',
  'FS',
  'GK',
  'HK',
  'IV',
  'K2',
  'KB',
  'KB(W)',
  'KLB',
  'KN',
  'MB',
  'RIV',
  'S',
  'SC',
  'SK',
  'ST',
  'TKLB',
  'TM',
  'WL',
  'Mr Copy',
  'Double A',
  'miilk',
  '한솔카피',
  'CWB',
  'ACB',
  'MFC',
];
export const PAPER_TYPE = [
  'Hi-Q 밀레니엄아트',
  'Hi-Q 밀레니엄아트(W)',
  'Hi-Q 듀오매트',
  'Hi-Q 듀오매트(W)',
  'Hi-Q Titan아트ECO',
  '화인코트GLOSS',
  'Hi-Q 편면아트지',
  'Hi-Q 미스틱',
  '화인코트 블루',
  '화인코트 블루(W)',
  '뉴플러스(백색)',
  '뉴플러스블루(백색)',
  '네오★아트',
  '네오★스노우화이트',
  '네오★스노우화이트(M)',
  '네오★WEB',
  '네오★하이글로스WEB',
  'Hi-Q SC',
  'SC',
  'SC Manilla',
  'Hi-Q ACB',
  'ACB',
  'ACB Manilla',
  'IV',
  'CCP',
  '레자크',
  '네오★CCP',
  'AB',
  '엑스프리',
  '파이넥스플러스(아트)',
  '뉴-백상',
  '네오★백상',
  '네오★미색',
  '크린유광',
  '네오★S플러스(백색)',
  'M-매트(백색)',
  'Mr Copy',
  'Double A',
  'miilk',
  '한솔카피',
];
export const PRODUCT = [
  ['산업용지', 'SC', 'Hi-Q SC', '한솔제지'],
  ['산업용지', 'SC', 'SC', '세하'],
  ['산업용지', 'SC', 'SC Manilla', '한창제지'],
  ['산업용지', 'SC', 'SC Manilla', '깨끗한나라'],
  ['산업용지', 'ACB', 'Hi-Q ACB', '한솔제지'],
  ['산업용지', 'ACB', 'ACB', '세하'],
  ['산업용지', 'ACB', 'ACB Manilla', '한창제지'],
  ['산업용지', 'ACB', 'ACB Manilla', '깨끗한나라'],
  ['산업용지', 'IV', 'IV', '한솔제지'],
  ['산업용지', 'IV', 'IV', '깨끗한나라'],
  ['산업용지', 'AB', 'AB', '한솔제지'],
  ['산업용지', 'CCP', 'CCP', '세하'],
  ['산업용지', 'CCP', '네오★CCP', '무림페이퍼'],
  ['인쇄용지', '아트지', 'Hi-Q 밀레니엄아트', '한솔제지'],
  ['인쇄용지', '아트지', '네오★아트', '무림페이퍼'],
  ['인쇄용지', '아트지', '네오★아트', '무림P&P'],
  ['인쇄용지', '아트지', '엑스프리', '한국제지'],
  ['인쇄용지', '아트지', '파이넥스플러스(아트)', '홍원제지'],
  ['인쇄용지', '백상지', '뉴-백상', '한솔제지'],
  ['인쇄용지', '백상지', '네오★백상', '무림페이퍼'],
  ['인쇄용지', '백상지', '네오★미색', '무림페이퍼'],
  ['인쇄용지', '백상지', '크린유광', '한국제지'],
  ['인쇄용지', 'MFC', '뉴플러스(백색)', '한솔제지'],
  ['인쇄용지', 'MFC', '뉴플러스블루(백색)', '한솔제지'],
  ['인쇄용지', 'MFC', '네오★S플러스(백색)', '무림페이퍼'],
  ['인쇄용지', 'MFC', 'M-매트(백색)', '한국제지'],
  ['복사용지', 'Mr Copy', 'Mr Copy', '무림페이퍼'],
  ['복사용지', 'Double A', 'Double A', 'Double A'],
  ['복사용지', 'miilk', 'miilk', '한국제지'],
  ['복사용지', '한솔카피', '한솔카피', '한솔제지'],
];
export const PAPER_COLOR_GROUP = ['A', 'B', 'C', '특', '양면'];
export const PAPER_COLOR = [
  'Greyback',
  'ExtraWhite',
  'SuperWhite',
  '연미색',
  '연노랑색',
  '연분홍색',
  '연연두색',
  '연옥색',
  '분홍색',
  '연두색',
  '옥색',
  '황색',
  '뉴크림색',
  '뉴계란색',
  'H-백색',
  '건빵색',
  '굴색',
  '금발색',
  '노랑색',
  '모래색',
  '밍크색',
  '백옥색',
  '벼색',
  '벚꽃색',
  '베이지색',
  '하늘색',
  '청회색',
  '크림색',
  '우유색',
  '쥐색',
];
export const PAPER_PATTERN = [
  '레자크 학무늬',
  '마메이드',
  '탄트',
  '레이트',
  '딤플',
  '레자크 210',
  '레자크 205',
  '레자크 96',
  '레자크 94',
  '레자크 92X',
  '레자크 92',
  '레자크 93',
  '레자크 64',
  '레자크 66',
];
export const PAPER_CERT = ['PEFC', 'FSC', 'KFCC'];
export const DIEMETER = [
  [3, 0],
  [6, 0],
  [7, 0],
  [12, 0],
];
export const PER_PACKAGE = [
  [200, 10],
  [500, 5],
  [250, 10],
];
export const PER_REAM = [
  [250, 0],
  [125, 0],
  [100, 0],
];

export const COMPANY = [
  [
    '주식회사 삼지페이퍼',
    '6018134020',
    '0511231234',
    '0511231234',
    '김남훈',
    'SAMZ',
    '도매',
    '지류 외 잡화',
    '부산광역시 사상구 하신번영로 445',
  ],
  [
    '(주)더조은페이퍼',
    '1242412561',
    '0311231234',
    '0311231234',
    '이상봉',
    'TJEP',
    '제조',
    '종이류',
    '경기도 시흥시 매화산단로 48',
  ],
  [
    '주식회사 케이티피',
    '1232412631',
    '0212341234',
    '0212341234',
    '석광한',
    'KTP1',
    '도매',
    '무역',
    '서울특별시 성동구 상원길 36',
  ],
  [
    '타라유통(주)',
    '2188122088',
    '0212341234',
    '0212341234',
    '이재수',
    'TARA',
    '소매',
    '지류 외 잡화',
    '서울특별시 마포구 상암동 상암산로 34',
  ],
  [
    '피엘페이퍼(주)',
    '1606514612',
    '0511231234',
    '0511231234',
    '임중현',
    'PLPR',
    '부동산',
    '임대',
    '대구광역시 서구 달서천로 346',
  ],
  [
    '(주)삼지프린테크',
    '2174612374',
    '0551231234',
    '0551231234',
    '김정진',
    'SMZP',
    '도매',
    '지류 외 잡화',
    '경상남도 밀양시 산외면 남기동길 159',
  ],
  [
    '주식회사 한솔피앤에스',
    '5031278561',
    '0212341234',
    '0212341234',
    '강준석',
    'HPNS',
    '제조',
    '종이류',
    '서울특별시 중구 퇴계로 213',
  ],
  [
    '(주)페이퍼웨어',
    '3568701989',
    '0212341234',
    '0212341234',
    '김정현',
    'PPWR',
    '도매',
    '무역',
    '서울특별시 성동구 성수일로 8길 55',
  ],
  [
    '테스트회사',
    '1234567890',
    '0212341234',
    '0212341234',
    '김불닭',
    'TEST',
    '테스트',
    '테스트',
    '서울특별시 성동구 성수일로 8길 55',
  ],
];

export const USER = [
  [8, '김정현', 'paperware_kjh', 'kjh@paperware.kr'],
  [8, '박혜준', 'paperware_phj', 'phj@paperare.kr'],
  [8, '안형은', 'paperware_ahe', 'ahe@paperware.kr'],
  [8, '권진오', 'paperware_kjo', 'kjo@paperware.kr'],
  [1, '김정진', 'samziepaper_kjj', 'kjj@samziepaper.com'],
  [1, '김정현', 'samziepaper_kjh', 'kjh@samziepaper.com'],
  [2, '이상봉', 'tjep_lsb', 'lsb@tjep.com'],
  [2, '박지훈', 'tjep_pjh', 'pjh@tjep.com'],
  [6, '김남훈', 'samzieprintech_knh', 'knh@samzieprintech.com'],
  [6, '김정진', 'samzieprintech_kjj', 'kjj@samzieprintech.com'],
  [9, '안형은', 'test_ahe', 'ahe@test.com'],
  [9, '박혜준', 'test_phj', 'phj@test.com'],
  [9, '김정현', 'test_kjh', 'kjh@test.com'],
] as [number, string, string, string][];

export const WAREHOUSE = [
  [
    9,
    '공개창고1',
    '[[24015]] [[강원 철원군 동송읍 금학로210번길 4-7::4-7, Geumhak-ro 210beon-gil, Dongsong-eup, Cheorwon-gun, Gangwon-do, Korea]] [[강원 철원군 동송읍 이평리 683-18::683-18, Ipyeong-ri, Dongsong-eup, Cheorwon-gun, Gangwon-do, Korea]] [[]]',
    true,
  ],
  [
    9,
    '공개창고2',
    '[[04788]] [[서울 성동구 광나루로 142-24::142-24, Gwangnaru-ro, Seongdong-gu, Seoul, Korea]] [[서울 성동구 성수동1가 656-1172::656-1172, Seongsu-dong 1(il)-ga, Seongdong-gu, Seoul, Korea]] [[]]',
    true,
  ],
  [
    9,
    '비공개창고',
    '[[04788]] [[서울 성동구 광나루로 142-24::142-24, Gwangnaru-ro, Seongdong-gu, Seoul, Korea]] [[서울 성동구 성수동1가 656-1172::656-1172, Seongsu-dong 1(il)-ga, Seongdong-gu, Seoul, Korea]] [[]]',
    false,
  ],
] as [number, string, string, boolean][];

export const LOCATION = [
  [
    9,
    '자사도착지1',
    '[[24015]] [[강원 철원군 동송읍 금학로210번길 4-7::4-7, Geumhak-ro 210beon-gil, Dongsong-eup, Cheorwon-gun, Gangwon-do, Korea]] [[강원 철원군 동송읍 이평리 683-18::683-18, Ipyeong-ri, Dongsong-eup, Cheorwon-gun, Gangwon-do, Korea]] [[]]',
    false,
  ],
  [
    9,
    '자사도착지2',
    '[[04788]] [[서울 성동구 광나루로 142-24::142-24, Gwangnaru-ro, Seongdong-gu, Seoul, Korea]] [[서울 성동구 성수동1가 656-1172::656-1172, Seongsu-dong 1(il)-ga, Seongdong-gu, Seoul, Korea]] [[]]',
    false,
  ],
  [
    9,
    '기타도착지1',
    '[[08827]] [[서울 관악구 관악산나들길 149::149, Gwanaksannadeul-gil, Gwanak-gu, Seoul, Korea]] [[서울 관악구 신림동 산 56-2::56-2, mountain, Sillim-dong, Gwanak-gu, Seoul, Korea]] [[]]',
    true,
  ],
  [
    9,
    '기타도착지2',
    '[[14508]] [[경기 부천시 계남로 19::19, Gyenam-ro, Bucheon-si, Gyeonggi-do, Korea]] [[경기 부천시 상동 525-6::525-6, Sang-dong, Bucheon-si, Gyeonggi-do, Korea]] [[]]',
    true,
  ],
] as [number, string, string, boolean][];
