-- AlterTable
ALTER TABLE `Plan` MODIFY `type` ENUM('INHOUSE_CREATE', 'INHOUSE_MODIFY', 'INHOUSE_RELOCATION', 'INHOUSE_PROCESS', 'INHOUSE_STOCK_QUANTITY_CHANGE', 'TRADE_NORMAL_SELLER', 'TRADE_NORMAL_BUYER', 'TRADE_WITHDRAW_SELLER', 'TRADE_WITHDRAW_BUYER', 'TRADE_OUTSOURCE_PROCESS_SELLER', 'TRADE_OUTSOURCE_PROCESS_BUYER') NOT NULL;
